name: Test release build (Windows)

on:
  push:
    branches:
    - master2.x
    
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '11'
        
    - name: Build distribution
      working-directory: kam1n0-builds/windows/
      run: ./build-distribution.bat
      
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build installer
      working-directory: kam1n0-builds/windows/
      run: |
        $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
        light.exe
        heat.exe
        where heat.exe
        ./build-installers.bat
      
    - name: Building Kam1n0
      working-directory: kam1n0/
      run: |
        mvn -DskipTests clean package
        mvn -DskipTests package
    
    - name: Running Kam1n0
      working-directory: kam1n0/build-bins
      run: |
        java -jar -Xmx12G -Xss4m -Djdk.attach.allowAttachSelf=true --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.management.rmi/com.sun.jmx.remote.internal.rmi=ALL-UNNAMED --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED --add-exports java.sql/java.sql=ALL-UNNAMED --add-opens java.base/java.lang.module=ALL-UNNAMED --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/jdk.internal.math=ALL-UNNAMED --add-opens java.base/jdk.internal.module=ALL-UNNAMED --add-opens java.base/jdk.internal.util.jar=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED kam1n0-server.jar --start
        
